# -*- coding: utf-8 -*-
"""bake_roofscape.py — what is on top of the buildings, read off the photograph.

THE PROBLEM, STATED AS A MEASUREMENT. This app is a FLYOVER: the camera spends
its whole life above the city looking down, so the surface the viewer actually
sees most is roofs. Before this pass every one of the 2,220 buildings rendered
as a flat lid painted `rd`, and bake_detail.py derives `rd` as the building's
own wall 12% darker. Downtown Dallas therefore read as a pile of brown and grey
boxes with nothing on any of them, which is what the user reported.

The real thing is the opposite. Downtown Dallas roofs are pale grey built-up
gravel and white membrane, and every tower over about 60 m carries a mechanical
penthouse, a cooling-tower bank and a screened plant deck that break its
silhouette. The COLOUR half of that matters more than the clutter half: a
correctly coloured empty deck already stops the city looking like painted
cardboard, and it costs one flat polygon per building.

WHAT IS FACTUAL HERE AND WHAT IS NOT. Every drawn feature carries `src`:

    src = "m"   MEASURED. Position, size, orientation and colour read off z20
                Esri nadir imagery (0.126 m/px at this latitude — a 1.4 m
                condenser is 11 px across, which is why this works at all). The
                deck colour of every building is measured, without exception.
    src = "g"   GENERATED by rule, because the photograph showed nothing there.
                Only ever a stair/lift overrun, and only on a building tall
                enough to require one. Rule and reasoning below.

There is no third category. Nothing here is invented decoration on a roof the
photograph says is empty. HEIGHT is the exception that applies to everything: a
nadir photo cannot measure it, so every height in this file is a rule, and the
rules are stated where they are used.

THE VOCABULARY, derived from the imagery over this bbox before anything was
drawn:

    deck     the roof surface itself, inset inside the parapet, in its OWN
             measured colour. One polygon per building. This is the pass.
    cond     a split-system condenser, ~1.4 m square, ~1.0 m tall.
    unit     an AHU / large condenser / roof plant box, 5-34 m2, ~1.7 m.
    fan      a round exhaust or cooling-tower fan.
    duct     a run of ductwork or a pipe rack: long, thin, low.
    plant    a dark equipment field or louvre screen. Low and wide.
    phouse   a stair/lift/mechanical penthouse: large, bright, and tall enough
             to break the silhouette. The only kind that is ever generated.
    pool     rooftop water.

WHY THE CLUTTER IS SPLIT ACROSS TWO LAYERS. It is a per-building cost times
2,220 buildings, on an app whose graphics preset auto-detects and can land on
`performance`. So every feature carries `t` (LOD tier) and `d` (a keep-order in
0..1), js/roofs.js draws tier 0 from z14.5 and tier 1 only from z16.2, and
`MAX_FOR(area)` caps what any one roof draws, biggest first. Decks are 0.25 m
tall, so they add a top face and almost no side geometry.

WHERE THE MEASUREMENT LIVES. scripts/bake_roofs.py owns the tile cache, the
sampler and the per-building survey, and this file imports them — see that
file's header for why the two bakes share one measurement instead of two copies
of it. `data/roof_survey.json` is that measurement; re-reading it costs ~12
minutes and this file's geometry costs ~20 seconds, and the geometry is what
needs iterating against renders.

Usage:  python scripts/bake_roofscape.py [--report]
        python scripts/bake_roofs.py --remeasure     # first, if the survey is stale
"""
import json
import math
import os
import sys
from collections import Counter

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from bake_roofs import (          # noqa: E402  — the survey and its geometry frame
    ROOT, MIN_H, MIN_AREA, PARAPET_IN, NO_ROOF_CLASSES,
    DST_LO, DST_HI, OSM_PITCHED,
    box, ccw, clean, clearance, deck_colour, h32, hero_names, index_osm, inset,
    like, load_survey, night_of, osm_roof_tags, pitched, poly_mask,
    signed_area, snapshot_path, temper, to_ll, to_m,
)

OUT = os.path.join(ROOT, "data", "roofscape.geojson")               # decks + tier 0
OUT_DETAIL = os.path.join(ROOT, "data", "roofscape.detail.geojson")  # tier 1, lazy

# ── The classifier ────────────────────────────────────────────────────
# Heights are the generative number in each row: a nadir photo cannot measure
# height, so each kind gets the height that kind of plant has.
KIND_H = {"cond": 1.0, "unit": 1.7, "fan": 2.1, "duct": 0.9,
          "plant": 1.5, "phouse": 3.0, "pool": 0.12}
# ...except on a high-rise, where it is wrong by a factor of three. A stair and
# lift overrun on a 40-storey tower has to clear the lift's own machine room and
# usually shares the enclosure with the cooling towers: on Renaissance Tower and
# Comerica the penthouse is visibly two to three storeys. Austin's flat 3.0 m
# came from a campus whose tallest building is 94 m, and applied here it laid a
# 3 m pad on top of a 200 m tower where the photograph shows a structure the
# size of a house. Scaled, clamped, and stated as a rule.
def PHOUSE_H(building_h):
    return min(9.5, 2.8 + 0.024 * building_h)


def PLANT_H(building_h):
    return min(3.4, 1.4 + 0.008 * building_h)


# Fallback colours, used only when a blob's own pixels are too dark to trust — a
# unit sitting in its own shadow reads near-black and would paint a hole.
KIND_COL = {"cond": "#8e8b84", "unit": "#a09c93", "fan": "#8a887f", "duct": "#a8a49a",
            "plant": "#5f5d58", "phouse": "#b0aa9e", "pool": "#4f8ea8"}
DARK_FLOOR = 46       # below this median luma, use the fallback instead

# WATER, AND WHY A PERMISSIVE MASK NEEDS A STRICT DECISION. "Blue" is not a
# water test in aerial imagery: a shadow is lit by the SKY, so every shadow on
# every roof has B > R — and downtown Dallas is full of shadow cast by 200 m
# towers. The survey's mask is deliberately permissive and the call is made
# here, against what the blobs turned out to be:
#
#     the median blob the mask calls "pool"   3.1 m2, luma 74, B-R 21
#     what a real rooftop pool looks like     >= 8 m2, bright, strongly blue
#
# Requiring all three at once takes 900-odd candidates down to a couple of dozen,
# which is roughly how many rooftop and courtyard pools this bbox actually has —
# the residential towers on the north side and the hotel decks.
POOL_MIN_M2 = 7.0
POOL_MIN_LUMA = 92.0
POOL_MIN_BR = 20.0

# ── The one generated kind ────────────────────────────────────────────
# A building tall enough to need a lift needs somewhere to terminate it. Where
# the photograph shows a roof with nothing of any size on it AND the building is
# at least this tall, one overrun is placed. Everything about it except its
# existence is a rule: size, and a corner picked from a hash of the building id
# so it is stable across bakes.
OVERRUN_MIN_H = 11.0      # ~3 office storeys; below that a roof hatch does the job
OVERRUN_W, OVERRUN_L = 4.6, 3.8

# How many blobs are actually DRAWN on one roof. A flat cap is the wrong shape:
# 46 units is nothing on a 6,000 m2 office floorplate and far too many on a
# 200 m2 shopfront. Scaling with area keeps the DENSITY roughly constant, which
# is what the eye reads; biggest first, so what survives is what shows from the
# air. The `d` keep-order then lets the density knob thin these further at run
# time without a re-bake.
def MAX_FOR(area_m2):
    return int(max(10, min(96, area_m2 / 85.0)))


# LOD. `t=0` is what reads from flying altitude; `t=1` waits until it is
# information rather than noise. Tier is decided by SIZE, not by kind — a big
# condenser bank reads from the air and a small penthouse does not.
TIER0_M2 = 11.0
TIER0_HT = 2.4
# Two same-kind boxes at the same height sharing more than this fraction of the
# smaller one's area are one object detected twice. 0.35 rather than something
# near 1.0 because the two halves of a split louvre screen come back as two
# rectangles that each also cover the gap between them.
COPLANAR_COVER = 0.35
# ...and when they overlap by LESS than that they are two real objects that abut.
# Lift the later one instead of deleting something the photograph saw.
COPLANAR_STAGGER = 0.25


def main():
    report = "--report" in sys.argv
    date, snap = snapshot_path()
    feats = json.load(open(snap, encoding="utf-8"))["features"]
    cache = load_survey()
    if not cache:
        raise SystemExit("data/roof_survey.json is missing — run "
                         "`python scripts/bake_roofs.py --remeasure` first")
    heroes = hero_names()
    osm = index_osm(osm_roof_tags(), feats)

    out = []
    stats = Counter()
    rows = []
    for f in feats:
        p = f["properties"]
        bid = p.get("id")
        h = p.get("final_height") or 0
        if h < MIN_H:
            stats["too_short"] += 1
            continue
        if p.get("building_class") in NO_ROOF_CLASSES:
            stats["open_canopy"] += 1
            continue
        # The five hand-built towers own their own roofs; js/heroes-dallas.js
        # hides the snapshot original by name filter on `buildings-3d` and
        # `buildings-roof`, and these layers are a different source with no such
        # filter. See bake_roofs.py's hero_names().
        if (p.get("name") or "") in heroes:
            stats["hero_owns_this_roof"] += 1
            continue
        s = cache.get(str(bid))
        if not s:
            stats["no_imagery_or_too_small"] += 1
            continue
        # bake_roofs.py draws these as sloping facets from the wall top; a deck
        # on one would be a flat slab buried inside its own pitch.
        if pitched(p, s, osm.get(bid)):
            stats["pitched_roof"] += 1
            continue

        g = f["geometry"]
        rings = ([g["coordinates"][0]] if g["type"] == "Polygon"
                 else [q[0] for q in g["coordinates"]])
        ring = max(rings, key=len)
        if len(ring) < 4:
            continue
        lat0 = sum(q[1] for q in ring) / len(ring)

        # ── the deck ──────────────────────────────────────────────────
        # It sits ON the parapet cap js/app.js already draws (CAP_GEOM), inset
        # by PARAPET_IN, so the cap shows as a rim around it. ON rather than
        # INSIDE for the same reason the cap itself sits on the wall instead of
        # in it: two coplanar faces with different colours is textbook
        # z-fighting, and a phone's 16-bit depth buffer is what pays for it.
        lift = max(1.0, 0.015 * h)
        deck_b = round(h + lift, 2)
        deck_h = round(deck_b + 0.25, 2)
        pm = clean(to_m(ring, lat0))
        dr = inset(pm, PARAPET_IN) or inset(pm, 0.55)
        if dr is None:
            stats["deck_degenerate"] += 1
            continue
        dr = ccw(dr)
        rd, rg, rn = deck_colour(s, p)
        out.append({"type": "Feature",
                    "geometry": {"type": "Polygon",
                                 "coordinates": [to_ll(dr + [dr[0]], lat0)]},
                    "properties": {"k": "deck", "src": "m", "t": 0, "d": 0.0,
                                   "b": deck_b, "h": deck_h,
                                   "rd": rd, "rg": rg, "rn": rn}})
        stats["decks"] += 1

        # ── the clutter ───────────────────────────────────────────────
        th = s.get("theta", 0.0)
        cxm, cym = s["c"]
        poly = ccw(pm)
        biggest = 0.0
        draw = s["blobs"][:MAX_FOR(s["area"])]
        n = max(1, len(draw))
        # Rectangles already emitted on THIS roof, as (cx, cy, w, l, top), so a
        # second blob describing the same equipment can be recognised. The
        # detector labels connected components, and a big louvre screen with a
        # gap down the middle comes back as two of them; each is then drawn as
        # its oriented bounding rectangle, so the pair is two near-identical
        # rectangles of the same kind — therefore the same KIND_H, therefore the
        # same top height. Two coplanar top faces have no defined draw order and
        # the shared area breaks into a comb of scanlines that flips as the
        # camera moves.
        emitted = []
        for i, b in enumerate(draw):
            kind = b["k"]
            if kind == "pool":
                bc = b["c"]
                if (b["a"] < POOL_MIN_M2 or b.get("lm", 0) < POOL_MIN_LUMA or
                        (bc[2] - bc[0]) < POOL_MIN_BR):
                    stats["shadow_not_water"] += 1
                    continue
            w = max(0.8, b["w"]); l = max(0.8, b["l"])
            # A unit's blob includes its own shadow, which at a 55 deg sun is
            # about half its width again. Shrinking the small kinds back is the
            # difference between a tidy row of units and a row of slabs.
            if kind in ("cond", "unit", "fan"):
                w *= 0.80; l *= 0.80
            ht = (PHOUSE_H(h) if kind == "phouse" else
                  PLANT_H(h) if kind == "plant" else KIND_H.get(kind, 1.2))
            ccx, ccy = cxm + b["x"], cym + b["y"]
            # Never let a box hang over the parapet — a unit half off the roof
            # is the most obviously wrong thing a generated roof can do. But it
            # only has to fit on its SHORT axis to stay on, and the deck is
            # already inset PARAPET_IN before this is measured; requiring
            # `max(w,l)/2` of clearance threw away most of a real condenser row,
            # which sits a metre or two inside the parapet by design.
            if clearance((ccx, ccy), poly) < min(w, l) * 0.5 + 0.25:
                stats["clipped_at_parapet"] += 1
                continue
            top_h = round(deck_h + ht, 2)

            def _shared(ox_, oy_, ow, ol):
                dx, dy = ccx - ox_, ccy - oy_
                du = abs(dx * math.cos(th) + dy * math.sin(th))
                dv = abs(-dx * math.sin(th) + dy * math.cos(th))
                return (max(0.0, (w + ow) / 2.0 - du) *
                        max(0.0, (l + ol) / 2.0 - dv))

            dup = False
            for _ in range(4):
                bump = False
                for (ox_, oy_, ow, ol, otop) in emitted:
                    if abs(otop - top_h) > 0.005:
                        continue
                    shq = _shared(ox_, oy_, ow, ol)
                    if shq <= 0.0:
                        continue
                    if shq >= COPLANAR_COVER * max(w * l, 1e-6):
                        dup = True
                        break
                    # A PARTIAL overlap is two different objects that abut, so
                    # deleting one deletes something the photograph saw.
                    # Separate them in z instead: two adjacent equipment screens
                    # are not level in reality either, and 0.25 m is a fraction
                    # of a pixel from the flying camera while being far more
                    # than the depth buffer needs.
                    top_h = round(top_h + COPLANAR_STAGGER, 2)
                    bump = True
                    stats["coplanar_staggered"] += 1
                    break
                if dup or not bump:
                    break
            if dup:
                stats["coplanar_duplicate"] += 1
                continue

            lm = b.get("lm", 120)
            # Plant is metal and concrete: it lives in a narrower, cooler band
            # than the deck it stands on, and it must not out-shine a white
            # membrane roof or the roof reads as the shadow and the units as the
            # surface. Its own measured colour, mapped into that band.
            col = KIND_COL[kind] if lm < DARK_FLOOR else \
                temper(b["c"], p.get("rd"), toward=0.06, dst=(66, 168))
            if kind == "pool":
                col = KIND_COL["pool"]
            a = b["a"]
            tier = 0 if (a >= TIER0_M2 or ht >= TIER0_HT) else 1
            out.append({
                "type": "Feature",
                "geometry": {"type": "Polygon",
                             "coordinates": [to_ll(box(ccx, ccy, w, l, th), lat0)]},
                "properties": {
                    "k": kind, "src": "m", "t": tier,
                    # keep-order: 0 is always kept, 1 is dropped first. Biggest
                    # first, so turning the density knob down thins the specks
                    # and keeps the plant that actually reads.
                    "d": round(i / n, 3),
                    "b": deck_h, "h": top_h,
                    "rd": col,
                    "rg": like(col, p.get("rd"), p.get("rg")),
                    "rn": night_of(col, p.get("rn")),
                },
            })
            emitted.append((ccx, ccy, w, l, top_h))
            biggest = max(biggest, a)
            stats["k_" + kind] += 1

        # ── the one generated kind ────────────────────────────────────
        if h >= OVERRUN_MIN_H and biggest < 12.0:
            # The freest spot on the deck, sampled on a coarse grid, biased
            # toward a corner by a hash of the building id so a re-bake does not
            # look like the overruns moved. Anything nearer the parapet than
            # half its own width would hang over the edge.
            best, bp = -1.0, None
            xs = [q[0] for q in dr]; ys = [q[1] for q in dr]
            hsh = h32(bid)
            oh = PHOUSE_H(h)
            for gi in range(7):
                for gj in range(7):
                    px_ = min(xs) + (max(xs) - min(xs)) * (gi + 0.5) / 7
                    py_ = min(ys) + (max(ys) - min(ys)) * (gj + 0.5) / 7
                    if not poly_mask(dr, np.array([[px_]]), np.array([[py_]]))[0, 0]:
                        continue
                    c = clearance((px_, py_), poly)
                    if c < max(OVERRUN_W, OVERRUN_L) * 0.5 + 0.6:
                        continue
                    bias = ((gi * 7 + gj) ^ hsh) % 13
                    score = c + bias * 0.11
                    if score > best:
                        best, bp = score, (px_, py_)
            if bp:
                base = temper([168, 163, 152], p.get("rd"), toward=0.14)
                out.append({
                    "type": "Feature",
                    "geometry": {"type": "Polygon",
                                 "coordinates": [to_ll(box(bp[0], bp[1], OVERRUN_W,
                                                           OVERRUN_L, th), lat0)]},
                    "properties": {
                        "k": "phouse", "src": "g", "t": 0, "d": 0.0,
                        "b": deck_h, "h": round(deck_h + oh, 2),
                        "rd": base,
                        "rg": like(base, p.get("rd"), p.get("rg")),
                        "rn": night_of(base, p.get("rn")),
                    },
                })
                stats["generated_overruns"] += 1

        if report:
            rows.append((s["area"], len(s["blobs"]), rd, s["tex"],
                         (p.get("name") or "(unnamed)")))

    # TWO FILES, and the split is the LOD, not a tidy-up. Tier 1 — the
    # individual condensers and small ducts — is most of the feature count and
    # roughly two thirds of the bytes, and js/roofs.js draws none of it above
    # z16.2. Shipping it in the same document would make every flyover pay the
    # download and the worker re-tile for geometry it never shows.
    base = [q for q in out if q["properties"]["t"] == 0]
    detail = [q for q in out if q["properties"]["t"] != 0]
    with open(OUT, "w", encoding="utf-8") as fh:
        json.dump({"type": "FeatureCollection", "features": base}, fh, separators=(",", ":"))
    with open(OUT_DETAIL, "w", encoding="utf-8") as fh:
        json.dump({"type": "FeatureCollection", "features": detail}, fh, separators=(",", ":"))

    meas = sum(1 for q in out if q["properties"]["src"] == "m")
    print(json.dumps({
        "snapshot": date,
        "features": len(out),
        "measured": meas, "generated": len(out) - meas,
        "tier0_from_z14_5": len(base), "tier1_from_z16_2": len(detail),
        "base_kb": round(os.path.getsize(OUT) / 1024, 1),
        "detail_kb_lazy": round(os.path.getsize(OUT_DETAIL) / 1024, 1),
        "counts": dict(sorted(stats.items())),
        "provenance": {
            "deck colour": "MEASURED - median of the 55-90th luma percentile inside "
                           "the parapet, z20 Esri nadir, tempered to scene exposure",
            "clutter position/size/orientation/colour":
                "MEASURED - local-background deviation blobs, oriented in the "
                "building's own frame",
            "every height in this file":
                "GENERATIVE - a nadir photo cannot measure height; each kind gets "
                "the height that kind of plant has, scaled with the building for "
                "penthouses and plant screens",
            "stair overruns":
                "GENERATIVE - only where the photograph showed a roof with nothing "
                "of any size on it, on a building >= %.0f m" % OVERRUN_MIN_H,
        },
    }, indent=2))
    if report:
        rows.sort(key=lambda r: -r[1])
        print("\n  area   n  deck      tex   building")
        for a, n_, c, t, nm in rows[:60]:
            print("  %5.0f %3d  %s  %.3f  %s" % (a, n_, c, t, nm[:44]))


if __name__ == "__main__":
    main()
